### ISSUE TITLE
Library seems to fail on yoast-generated sitemaps

### ISSUE THREAD

**Issue by minism** [capjamesg/getsitemap#5]
I haven't dug into why, but the library seems to return no results for websites that use yoast-generated sitemaps.

Examples:
- https://altonbrown.com/sitemap_index.xml
- https://www.davidlebovitz.com/sitemap_index.xml

Output:

    >>> print(getsitemap.retrieve_sitemap_urls('https://altonbrown.com'))
    []
    >>> print(getsitemap.get_individual_sitemap('https://altonbrown.com/recipes-sitemap.xml'))
    {}
    >>> print(getsitemap.retrieve_sitemap_urls('https://davidlebovitz.com'))
    []
    >>> print(getsitemap.retrieve_sitemap_urls('https://www.davidlebovitz.com/post-sitemap.xml'))
    []

**Comment by capjamesg** [comment]
I think it is time for me to write a test suite. I'll investigate this issue in the next 1-2 days and report back here. I haven't explicitly tested on Yoast sitemaps.

**Comment by capjamesg** [comment]
I tested on one of the sitemaps that you provided and noticed that it returned a 403 when a user agent was not specified. I am adding in a user agent feature which will be available in the next release of `getsitemap`. This will be released over the next day.

I have published the source code in the repository, so you can use the following command if you want to build the source yourself locally for use while you wait fo rthe release:

```
pip install -r requirements.txt
pip install -e .
```

**Comment by minism** [comment]
Awesome.  Thanks for the quick response!

**Comment by capjamesg** [comment]
The new release is live at https://pypi.org/project/getsitemap/0.1.5/. You can install it with `pip install getsitemap==0.1.5`. Let me know if you run into any issues!
